<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Contact Form Submission</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            line-height: 1.6; 
            color: #333; 
            max-width: 600px; 
            margin: 0 auto; 
            padding: 20px;
        }
        .header { 
            background-color: #2563eb; 
            color: white; 
            padding: 20px; 
            text-align: center; 
            border-radius: 8px 8px 0 0;
        }
        .content { 
            background-color: #f8fafc; 
            padding: 30px; 
            border-radius: 0 0 8px 8px;
        }
        .field-group { 
            margin-bottom: 20px; 
            border-bottom: 1px solid #e2e8f0; 
            padding-bottom: 15px;
        }
        .field-label { 
            font-weight: bold; 
            color: #374151; 
            margin-bottom: 5px;
        }
        .field-value { 
            background-color: white; 
            padding: 10px; 
            border-radius: 4px; 
            border: 1px solid #d1d5db;
        }
        .message-content { 
            white-space: pre-wrap; 
            max-height: 200px; 
            overflow-y: auto;
        }
        .footer { 
            margin-top: 30px; 
            padding-top: 20px; 
            border-top: 2px solid #e2e8f0; 
            font-size: 14px; 
            color: #6b7280;
        }
        .reference { 
            background-color: #dbeafe; 
            padding: 10px; 
            border-radius: 4px; 
            margin: 20px 0;
            text-align: center;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>🚐 FiveStars Transport</h2>
        <h3>New Contact Form Submission</h3>
    </div>
    
    <div class="content">
        <div class="reference">
            Reference #{{ $referenceNumber }}
        </div>

        <div class="field-group">
            <div class="field-label">Name:</div>
            <div class="field-value">{{ $contact->name }}</div>
        </div>

        <div class="field-group">
            <div class="field-label">Email:</div>
            <div class="field-value">
                <a href="mailto:{{ $contact->email }}">{{ $contact->email }}</a>
            </div>
        </div>

        @if($contact->phone)
        <div class="field-group">
            <div class="field-label">Phone:</div>
            <div class="field-value">
                <a href="tel:{{ $contact->phone }}">{{ $contact->phone }}</a>
            </div>
        </div>
        @endif

        <div class="field-group">
            <div class="field-label">Subject:</div>
            <div class="field-value">{{ $contact->subject }}</div>
        </div>

        <div class="field-group">
            <div class="field-label">Message:</div>
            <div class="field-value message-content">{{ $contact->message }}</div>
        </div>

        <div class="field-group">
            <div class="field-label">Submitted:</div>
            <div class="field-value">{{ $contact->created_at->format('M j, Y \a\t g:i A') }}</div>
        </div>

        @if($contact->ip_address)
        <div class="field-group">
            <div class="field-label">IP Address:</div>
            <div class="field-value">{{ $contact->ip_address }}</div>
        </div>
        @endif
    </div>

    <div class="footer">
        <p><strong>Next Steps:</strong></p>
        <ul>
            <li>Reply to the customer within 24 hours</li>
            <li>Mark as "replied" in the admin dashboard</li>
            <li>Follow up if it's a booking inquiry</li>
        </ul>
        
        <p style="margin-top: 20px;">
            <small>This email was automatically generated by the FiveStars Transport contact form system.</small>
        </p>
    </div>
</body>
</html>