FiveStars Transport - New Contact Form Submission

Reference: {{ $referenceNumber }}

Contact Details:
- Name: {{ $contact->name }}
- Email: {{ $contact->email }}
@if($contact->phone)- Phone: {{ $contact->phone }}
@endif
- Subject: {{ $contact->subject }}
- Submitted: {{ $contact->created_at->format('M j, Y \a\t g:i A') }}

Message:
{{ $contact->message }}

@if($contact->ip_address)
IP Address: {{ $contact->ip_address }}
@endif

Next Steps:
- Reply to the customer within 24 hours
- Mark as "replied" in the admin dashboard
- Follow up if it's a booking inquiry

This email was automatically generated by the FiveStars Transport contact form system.