FiveStars Transport - New Group Quote Request

Reference #{{ $referenceNumber }}

PRIORITY REQUEST: Group booking for {{ $data['group_size'] }} passengers on {{ \Carbon\Carbon::parse($data['event_date'])->format('M j, Y') }}

GROUP INFORMATION:
- Group Size: {{ $data['group_size'] }} passengers
- Event Date: {{ \Carbon\Carbon::parse($data['event_date'])->format('l, M j, Y') }}
- Service Type: {{ $data['service_type'] }}

CONTACT DETAILS:
- Name: {{ $data['contact_name'] }}
- Email: {{ $contact->email }}
@if($data['phone'])- Phone: {{ $data['phone'] }}@endif

EVENT DETAILS:
{{ $data['event_details'] }}

SUBMISSION INFO:
- Submitted: {{ $contact->created_at->format('M j, Y \a\t g:i A') }}
@if($contact->ip_address)- IP Address: {{ $contact->ip_address }}@endif

NEXT STEPS FOR GROUP QUOTE:
⏰ Within 4 hours: Send acknowledgment email to customer
⏰ Within 24 hours: Prepare detailed quote with vehicle options
📋 Include: Pricing breakdown, vehicle specifications, pickup/drop-off details
📞 Follow up: Call customer to discuss specific requirements

RECOMMENDED ACTION: Call customer within 2 hours for group bookings over 20 passengers

This email was automatically generated by the FiveStars Transport group quote system.